<a href="https://colab.research.google.com/github/entangelk/study_AIs/blob/main/docs/MLs/Regression/01_linearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Regression (회귀) 예측


## 데이터 관련
- 데이터
- 모델
- 평가

In [2]:
from sklearn import datasets
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)  # 대문자는 여러개니까, 소문자는 하나니까

In [3]:
type(diabetes_X), type(diabetes_y) # numpy로 이루어짐

(numpy.ndarray, numpy.ndarray)

In [4]:
diabetes_X.shape, diabetes_y.shape # sahpe =  행과 열의 갯수를 알려줌

((442, 10), (442,))

### 모델

In [5]:
from sklearn import linear_model # 학습모델 선택 (선형모델)

In [9]:
linearRegression = linear_model.LinearRegression() # 학습모델(선형모델)중 분류(일반선형모델) 선택

In [10]:
linearRegression.fit(diabetes_X, diabetes_y) # 학습 진행

LinearRegression()

### 평가

In [12]:
diabetes_X[:2], diabetes_y[:2]

(array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
         -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
         -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405]]),
 array([151.,  75.]))

In [13]:
linearRegression.predict(diabetes_X[:2])

array([206.11667725,  68.07103297])