In [1]:
!pip install -U pandas

In [2]:
import pandas as pd

In [3]:
import pyLDAvis
import pyLDAvis.lda_model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import fetch_20newsgroups
# 데이터 로드
data = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))
documents = data.data

In [4]:
documents[:2]

['I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.',
 "A fair number of brave souls who upgraded their SI clock oscillator have\nshared their experiences for this poll. Please send a brief message detailing\nyour experiences with the procedure. Top speed attained, CPU rated speed,\nadd on cards and adapters, heat sinks, hour of usage per day, floppy disk\nfunctionality with 800 and 1.4 m floppies are especially requested.\n\nI will be summarizing in the next two days, so please add to the network\nknowledge base if you have done the clock upgrade and haven't an

### TfidfVectorizer options
반복되는것과 반복되지 않는것을 거르는데 사용 - 파라미터 -> 소수(확률), 정수(갯수)
- max_df : 이상이면 빼버려라 (너무 많아서 쓸모 없을 때)
- min_df : 이하면 빼버려라 (너무 적어서 쓸모 없을 때)

In [5]:
tfidfVectorizer = TfidfVectorizer(stop_words='english',max_df=0.95, min_df=2)

In [6]:
tfidf = tfidfVectorizer.fit_transform(documents)
tfidf.toarray()[:2]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
import numpy as np
np.where(tfidf.toarray()[:2] > 0)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([ 2582,  2918,  4348,  7279,  7618,  7843,  8160,  8308, 11269,
        12709, 12710, 13133, 13725, 13755, 15821, 17670, 18895, 20611,
        20958, 21663, 21665, 22151, 23553, 27879, 29041, 29858, 30936,
        31406, 32237, 32669, 32807, 37946, 38743,  3196,  4331,  4337,
         5227,  5944,  6525,  7537,  7627,  8332,  9269, 10550, 11269,
        11275, 11885, 12357, 14043, 14405, 14669, 15286, 15287, 15799,
        17292, 17383, 17941, 20618, 22958, 24577, 25052, 25772, 27289,
        27841, 28894, 29729, 31367, 31603, 31843, 31988, 32523, 32693,
        33693, 34611, 36280, 36282, 36350]))

In [8]:
latentDirichletAllocation = LatentDirichletAllocation(n_components=5,n_jobs=-1)

In [9]:
latentDirichletAllocation_seven = LatentDirichletAllocation(n_components=7,n_jobs=-1)

In [10]:
latentDirichletAllocation_three = LatentDirichletAllocation(n_components=3,n_jobs=-1)

In [11]:
latentDirichletAllocation.fit(tfidf)

LatentDirichletAllocation(n_components=5, n_jobs=-1)

In [12]:
latentDirichletAllocation_three.fit(tfidf)

LatentDirichletAllocation(n_components=3, n_jobs=-1)

In [13]:
latentDirichletAllocation_seven.fit(tfidf)

LatentDirichletAllocation(n_components=7, n_jobs=-1)

In [14]:
vis_five = pyLDAvis.lda_model.prepare(latentDirichletAllocation, tfidf, tfidfVectorizer)
vis_seven = pyLDAvis.lda_model.prepare(latentDirichletAllocation_seven, tfidf, tfidfVectorizer)
vis_three = pyLDAvis.lda_model.prepare(latentDirichletAllocation_three, tfidf, tfidfVectorizer)

In [15]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis_five)

In [16]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis_seven)

In [17]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis_three)